name: Deploy
on:
  release:
    types: [published]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Prepate Git Repo
        uses: actions/checkout@v2

      - name: ☕ Install OpenJDK
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64

      - name: 🚀 Deploy to Releases
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'target/*.jar'
          repo-token: ${{ secrets.GITHUB_TOKEN }}